#!/bin/bash

if [ -z $1 ]; then
    echo "Usage: $0 [INPUTFILE]"
    echo "[INPUTFILE]: The results text file generated by step 3." 
    exit 1
fi

INPUTFILE=$1
COMPUT=comput.txt
PICDIR=Pictures

echo "Check if the file exist..."

if [ -e $1 ] 
then
    echo "The necessary file exist!"

    echo "Separate data file comes from step 3..."
    root -q -b -l separate_1.C\(\"$1\"\)

    echo "Doing calculation..."
    root -q -b -l callcalc_2.C

    echo "Ploting results..."
    root -q -b -l plotresults_3.C\(\"$COMPUT\"\)

    echo "Collecting the output files"
    newname=`echo $1 | cut -f1 -d'.'`
    rename -v s/output/$newname\_out/ output.*

    echo "Removing unnecessary files"
    rm results*.txt
    rm $COMPUT

    if [ -e $PICDIR ]
    then
	echo "Directory for picture files exits!"
    else
	mkdir $PICDIR
    fi
    
    mv $newname\_out.pdf $PICDIR

else
    echo "File doesn't exist!"
    exit 2

fi
